### ISSUE TITLE
首页 OSS 资源迁移

### ISSUE THREAD

**Issue by China-Link** [waiting0201/vmChina#4]
![20321723546521_ pic](https://github.com/user-attachments/assets/bbd1d02e-0468-4c62-8a55-ef7b754fffbf)
![20341723546538_ pic](https://github.com/user-attachments/assets/2cd98078-1fc6-4f71-8d06-d3b4de31c714)
![20351723546548_ pic](https://github.com/user-attachments/assets/687704b5-5f34-4bf7-9707-ad987d1a2b7c)
![20361723546566_ pic](https://github.com/user-attachments/assets/dbc2d177-5cec-431d-9fa3-cb5cc48a7b68)

**Comment by waiting0201** [comment]
已遷移
